twitter:
  api_key: "your_twitter_api_key"
  api_secret_key: "your_twitter_api_secret_key"
  access_token: "your_access_token"
  access_secret: "your_access_secret"
nostr:
  private_key: "your_nostr_private_key"
  public_key: "your_nostr_private_key"  # Optional if you derive it from the private key